version: "3.8"

x-node-env: &node-env
    image: node:16.8.0
    user: node
    ports:
        - "8080:8000"
    volumes:
        - .:/app
        - node-16:/home/node/.npm
    working_dir: "/app"
    environment:
        TZ: "Europe/Prague"
    networks:
        - spotter-app-network

services:
    node-app:
        <<: *node-env
        command: |
            bash -c "
                sleep 3 &&
                npm ci &&
                npm start
            "
    mongo:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        env_file: .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            - spotter-app-network
        volumes:
            - spotter:/data/db
        ports:
            - "27017:27017"

networks:
    spotter-app-network:
        driver: bridge

volumes:
    node-16:
        external: true
    spotter:
