name: Deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: d6bd6071-39b5-4502-b708-23621b419f43
          heroku_app_name: nevermore-spotter-bot
          heroku_email: krystof.liskovec@gmail.com
          env_file: .env
          branch: production
          dontuseforce: true
          dontautocreate: true
          usedocker: true
          docker_heroku_process_type: worker
